"""add user role and login tracking

Revision ID: b7c41d92e08a
Revises: af256f19c710
Create Date: 2026-08-23 01:52:00.000000

Written by hand rather than autogenerated: autogenerate needs a live
Postgres to diff against, and the zero-infra dev mode runs on SQLite where
`create_all` owns the schema instead. Verified column-by-column against
`app/models/user.py`.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'b7c41d92e08a'
down_revision: Union[str, None] = 'af256f19c710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default is what makes this safe on a table that already has
    # rows: existing users get 'user'/0 written by the ALTER itself, so the
    # NOT NULL constraint holds from the moment the column exists.
    op.add_column(
        'users',
        sa.Column('role', sa.String(length=20), nullable=False, server_default='user'),
    )
    op.add_column(
        'users',
        sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        'users',
        sa.Column('login_count', sa.Integer(), nullable=False, server_default='0'),
    )
    # Every admin-dashboard query filters or groups on role; the table is
    # small today but this is the one column guaranteed to be scanned on
    # every admin request.
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'login_count')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'role')
